### ISSUE TITLE
Playing Halo 2 Campaign causes the script to crash

### ISSUE THREAD

**Issue by RunDevilRun007** [kay-el-zed/HaloMCC-DiscordRPC#15]
When playing Halo 2 Campaign the application stops working and outputs the following errors:

`Traceback (most recent call last):
  File "ui.py", line 98, in <module>
  File "ui.py", line 9, in main
  File "ui.py", line 33, in option
  File "richpresence.py", line 128, in main
KeyError: 'Normal'
[44116] Failed to execute script ui
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x00000266D6940EE8>
Traceback (most recent call last):
  File "asyncio\proactor_events.py", line 93, in __del__
  File "asyncio\proactor_events.py", line 57, in __repr__
  File "asyncio\windows_utils.py", line 102, in fileno
ValueError: I/O operation on closed pipe
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x00000266D6940EE8>
Traceback (most recent call last):
  File "asyncio\proactor_events.py", line 93, in __del__
  File "asyncio\proactor_events.py", line 57, in __repr__
  File "asyncio\windows_utils.py", line 102, in fileno
ValueError: I/O operation on closed pipe`

Only happens with Halo 2 Campaign as far as I can tell

**Comment by Gurrman375** [comment]
Could you get a screen recording of the issue? @RunDevilRun007
It might be the level that is being ran
