### ISSUE TITLE
Rich Presence broke after going into ODST Forge

### ISSUE THREAD

**Issue by LOL-DUDE-64** [kay-el-zed/HaloMCC-DiscordRPC#22]
The error I got is as follows, which repeated a few times:
`Traceback (most recent call last):
  File "ui.py", line 98, in <module>
  File "ui.py", line 9, in main
  File "ui.py", line 33, in option
  File "richpresence.py", line 95, in main
KeyError: 'Assault on the Control Room'
[20392] Failed to execute script ui
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0000024EF9590EE8>
Traceback (most recent call last):
  File "asyncio\proactor_events.py", line 93, in __del__
  File "asyncio\proactor_events.py", line 57, in __repr__
  File "asyncio\windows_utils.py", line 102, in fileno
ValueError: I/O operation on closed pipe`

**Comment by Gurrman375** [comment]
I haven't set proper conditions for forge. The way it currently runs is by looking through a library to gather what the player is playing and show the image.

I'm doing a full rewrite so I'll tackle this issue in the rewrite. I don't have an eta but it should be soon.
